global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK_URL'
  email_smarthost: 'smtp.gmail.com:587'
  email_from: 'alerts@college-website.com'
  email_auth_username: 'alerts@college-website.com'
  email_auth_password: 'YOUR_EMAIL_PASSWORD'

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'slack-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'email-notifications'
      continue: true

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#alerts'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        actions:
          - type: button
            text: 'View in Grafana'
            url: 'http://localhost:3000/d/college-website/college-website-dashboard'

  - name: 'email-notifications'
    email_configs:
      - to: 'admin@college-website.com'
        send_resolved: true
        headers:
          subject: '{{ template "email.default.subject" . }}'
        html: '{{ template "email.default.html" . }}'

templates:
  - '/etc/alertmanager/templates/*.tmpl' 