global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "college-website"
    metrics_path: "/api/metrics"
    static_configs:
      - targets: ["localhost:3000"]
    scrape_interval: 5s
    scrape_timeout: 4s

  - job_name: "node-exporter"
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["localhost:9187"]

  - job_name: "redis-exporter"
    static_configs:
      - targets: ["localhost:9121"]

  - job_name: "elasticsearch-exporter"
    static_configs:
      - targets: ["localhost:9114"]

  - job_name: "mongodb-exporter"
    static_configs:
      - targets: ["localhost:9216"]

  - job_name: "alertmanager"
    static_configs:
      - targets: ["localhost:9093"] 