apiVersion: apps/v1
kind: Deployment
metadata:
  name: college-website
  labels:
    app: college-website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: college-website
  template:
    metadata:
      labels:
        app: college-website
    spec:
      containers:
      - name: college-website
        image: college-website:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-secrets
              key: redis-url
        - name: ELASTICSEARCH_URL
          valueFrom:
            secretKeyRef:
              name: elasticsearch-secrets
              key: elasticsearch-url
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets
              key: mongodb-url
---
apiVersion: v1
kind: Service
metadata:
  name: college-website
spec:
  selector:
    app: college-website
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: college-website
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: college-website
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 